version: '3'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=packify
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=packify
      - DATABASE_HOST=localhost
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - dev


volumes:
  postgres:

networks:
  dev:
    external: true