# fly.toml app configuration file generated for packify on 2025-04-27T17:55:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'packify'
primary_region = 'otp'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
